Repository HNTQ/Movie-Search-CS50, pull requests merged in 2021-06, with the labels that each got.

#9 Feature: add the login_required decorator to required routes
  .idea/Movie-Search-CS50.iml
  app.py
  helpers.py
Labels: enhancement

#10 Feature: add the error handling function
  app.py
  helpers.py
  templates/errors.html
Labels: enhancement

#13 Feature: Movies lookup api request
  api.py
  app.py
  templates/index.html
  templates/results.html
  templates/search.html
Labels: enhancement

#14 Maintenance: removing database from remote
  .gitignore
  README.md
  application.db
Labels: 🔧 Maintenance

#15 Release V1.b: Add login procedure, basic API call and main routes 🎉
  .gitignore
  .idea/Movie-Search-CS50.iml
  .idea/misc.xml
  README.md
  api.py
  app.py
  application.db
  helpers.py
  templates/activation.html
  templates/errors.html
  templates/index.html
  templates/layout.html
  templates/login.html
  templates/profil.html
  templates/register.html
  templates/results.html
  templates/scripts/passirate.js
  templates/search.html
Labels: 🎉 Release

#16 Feature/movie details
  .idea/sqldialects.xml
  api.py
  app.py
  helpers.py
  requirements.txt
  templates/details.html
  templates/layout.html
  templates/profile.html
  templates/search.html
Labels: enhancement
